### ISSUE TITLE
Unable to display some Unicode characters

### ISSUE THREAD

**Issue by jurichmitchell** [robertodoering/harpy#606] opened 2022-03-16 18:36 UTC
I'm not sure how many characters in total are affected, but I have found at least one Unicode character that displays as the Replacement Glyph in app.

U+2E2E :  Backwards Question Mark (aka Irony/Sarcasm Punctuation) ⸮

Most probable cause would be the font lacking this character.

**Comment by robertodoering** [comment] 2022-03-17 11:31
Duplicate of [#495](https://github.com/robertodoering/harpy/issues/495)

**Closed by robertodoering** 2022-03-17 11:31 UTC
Labels: bug :lady_beetle:
