### ISSUE TITLE
Collapse long reply thread's

### ISSUE THREAD

**Issue by dnestico** [robertodoering/harpy#579] opened 2022-02-16 06:17 UTC
So to avoid super long reply thread's in the notifications tab could you add a feature that automatically collapses the thread with maybe an expand button after let's say 3 replies? 

VIDEO Link here cuz was too big to upload here somehow... https://photos.app.goo.gl/ZNzL9D91PayBL24v9

**Comment by robertodoering** [comment] 2022-02-16 13:40
Great suggestion, yes that makes a lot of sense and it would also help with #513.
Thanks 👍

**Comment by robertodoering** [comment] 2022-06-07 11:02
Just realized this is a duplicate of #391. Will close this one in favor of the old one

**Closed by robertodoering** 2022-06-07 11:02 UTC
Labels: feature :balloon:
