### ISSUE TITLE
videos and photos are not displayed in the feed.

### ISSUE THREAD

**Issue by Valturion** [robertodoering/harpy#677] opened 2022-05-30 19:29 UTC
### Bug description 

---
### Expected behavior

---
### Steps to reproduce

---

**Comment by Valturion** [comment] 2022-05-30 19:29
Android 6.1

**Comment by robertodoering** [comment] 2022-06-07 10:36
Can't reproduce this and I'm not aware of anyone else having the same issue.
Please make sure you can reach Twitter's media server (`pbs.twimg.com`) from your device or check that this wasn't a temporary issue.

I'll close this issue but feel free to comment with steps to reproduce this issue if it persists.

**Closed by robertodoering** 2022-06-07 10:36 UTC
Labels: bug :lady_beetle:
