### ISSUE TITLE
Image downloading issue 

### ISSUE THREAD

**Issue by Biano0915** [robertodoering/harpy#529] opened 2022-01-18 08:34 UTC
Hi there,
I recently started to use harpy as my main twitter app and it has done great so far.
But I have been encountering the issue that I cannot download the image from twitter posts sometimes.
I tried both the "Pictures" & "Download" file paths but I just couldn't save the image into my phone, 
However, sometimes the image would pop out in my photo app after a couple of minutes but that happened less, most of the time it fails.

I'm using the Pixel 6 with the newest January update btw.

English isn't my first language so I tried my best to describe it
Hope it can be fixed

**Comment by Biano0915** [comment] 2022-01-18 09:04
I kind of figure it out
The download location must be "/storage/emulated/O/Download", "/storage/emulated/O/Pictures" won't work
But even if I choose the "Download", I still need to go to the file app to make sure the image is in my device then I can see it in my photo app.
A little weird.

**Comment by FerasK0** [comment] 2022-01-18 09:19
I agree, faced the same problem

**Comment by robertodoering** [comment] 2022-06-07 10:38
This was a duplicate of #574 and fixed in 0.9.0.

If you still have issues with downloading feel free to open a new issue

**Closed by robertodoering** 2022-06-07 10:38 UTC
