### ISSUE TITLE
Maintain timeline position on refresh

### ISSUE THREAD

**Issue by monee121** [robertodoering/harpy#652] opened 2022-05-15 10:50 UTC
When refreshing the home TL, maintain the current position and then load more tweets without automatically going to the top. This way you don't have to remember where you were on the TL and therefore don't miss any tweets. I hope this makes sense. See image attached. I usually use Fenix and this is a screenshot of when I refresh. My original position is maintained, there is text that tells me how many tweets were loaded, and also a scroll bar on the side (blue) that shows how far to scroll to the top.

![Screenshot_20220514-083341_Fenix.jpg](https://user-images.githubusercontent.com/105255608/168469046-b2bba0b9-06c5-4008-9ae3-20f8809ef21d.jpg)

**Comment by robertodoering** [comment] 2022-05-15 11:33
Duplicate of #323
Please open a discussion for feature requests instead of an issue

**Closed by robertodoering** 2022-05-15 11:33 UTC
