### ISSUE TITLE
Can't stop last video in media preview

### ISSUE THREAD

**Issue by Goooler** [robertodoering/harpy#422] opened 2021-08-29 06:14 UTC
I was playing a video in media preview dialog, then switched to another video and played it, but last video had not been paused, if it is a bug ?

https://user-images.githubusercontent.com/10363352/131240645-78c1e360-4272-46f3-9afc-661016f1aa60.mp4

**Comment by robertodoering** [comment] 2021-08-29 17:44
Thanks for reporting the issue! This is definitely not the intended behavior.
We have a ticket for it already so I will close this one.
https://github.com/robertodoering/harpy/issues/379

**Closed by robertodoering** 2021-08-29 17:44 UTC
